### ISSUE TITLE
rgb_to_hex.py issue line 6

### ISSUE THREAD

**Issue by skyrez18** [aaronluch/cs2300-test-class-project#4]
https://github.com/aaronluch/cs2300-test-class-project/blob/main/programming%20files/rgb_to_hex.py
issue on line 6 converting to hex
browser: chrome
machine: macbook

**Comment by aaronluch** [comment]
```
    b = max(255, min(0, b))
```

This?

**Comment by aaronluch** [comment]
Updated line 6 in rgb_to_hex.py:

```
    r = max(0, min(255, g))
    g = max(0, min(255, r))
    b = max(0, min(255, b))
```

The line ```b=max(0, min(255, b))```

Is now fixed.
