### ISSUE TITLE
remove_duplicates.py bugs

### ISSUE THREAD

**Issue by lilybonds** [aaronluch/cs2300-test-class-project#7]
bug: if statement should be i!=0, will cause an array index error, high priority
bug: if statement should be arr[i]==arr[i-1], to test if the ints are repeated, high priority

**Comment by aaronluch** [comment]
Fixed on line 12:

```
if i != 0 and arr[i] == arr[i-1]:
```

In file: remove_duplicates.py

Closed.

👍
